version: '3.12'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"  # localhost:8000 → container:8000
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  # localhost:5173 → container:5173
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./frontend:/app  # <-- bind mount your code
      - /app/node_modules  # <-- ignore host node_modules to avoid conflicts
    command: npm run dev -- --host
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true  # for hot reloading in Docker

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
