"""Setup Favorite

Revision ID: b026ed108cfd
Revises: 
Create Date: 2025-05-18 22:43:07.794285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b026ed108cfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_movies',
    sa.Column('favorite_movie_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('favorite_movie_id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='unique_favorite_movie')
    )
    op.create_table('ratings',
    sa.Column('rating_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rating_id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='unique_rating')
    )
    op.create_table('rating_reviews',
    sa.Column('rating_review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('agreed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.rating_id'], ),
    sa.PrimaryKeyConstraint('rating_review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating_reviews')
    op.drop_table('ratings')
    op.drop_table('favorite_movies')
    # ### end Alembic commands ###
