"""favorite_service_setup

Revision ID: 8427c79bec23
Revises: 
Create Date: 2025-05-18 13:42:17.795326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8427c79bec23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('rating_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_table('rating_reviews',
    sa.Column('rating_review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('agreed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.rating_id'], ),
    sa.PrimaryKeyConstraint('rating_review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating_reviews')
    op.drop_table('ratings')
    # ### end Alembic commands ###
