name: CI - Lint & Type Check

on:
  push:

jobs:
  test-and-lint:
    name: Run mypy and pylint
    runs-on: ubuntu-latest
    env:
      TMDB_ACCESS_TOKEN: ${{ secrets.TMDB_ACCESS_TOKEN }}
      TMDB_ACCOUNT_ID: ${{ secrets.TMDB_ACCOUNT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r api/requirements.txt

      - name: Run pylint
        run: pylint api/src/ api/tests/

      - name: Run mypy
        run: mypy src/

      - name: Run pytest
        run: |
          pytest api/tests/
