name: CI - Full Project + Consume Api, Linting, Testing, Type Checking

on:
  push:

jobs:
  test-and-lint:
    name: Run mypy and pylint
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ vars.API_KEY }}
      TMDB_ACCOUNT_ID: ${{ vars.TMDB_ACCOUNT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
        working-directory: api

      - name: Run pylint
        run: pylint src/ tests/
        working-directory: api

      - name: Run mypy
        run: mypy src/
        working-directory: api

      - name: Run pytest
        run: |
          pytest api/tests

  run_full_project:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      TMDB_ACCOUNT_ID: ${{ secrets.TMDB_ACCOUNT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose (if needed)
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: run_full_project.sh
        run: |
          ./run_full_project.sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
        working-directory: api

      - name: Run consume_api_docker
        run: |
          python consume_api_docker.py
        working-directory: api
