name: CI - Linting, Testing, Type Checking

on:
  push:

jobs:
  test-and-lint:
    name: Run CI
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Run CI
        run: |
          ./check.sh

  run_full_project:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose (if needed)
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: run_microservices_docker.sh
        run: |
          ./run_microservices_docker.sh

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Run consume_api
        run: |
          python consume_script.py